#mysql数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mobile?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 1234
  #指定POJO扫描包来让mybatis自动扫描到自定义POJO
mybatis:
  type-aliases-package: com.example.model
  mapper-locations: /mapper/**.xml

#服务器端口号
server:
  port: 8080

